### ISSUE TITLE
How SLA are calculate ?

### ISSUE THREAD

**Issue by bzhpwr** [RealOpInsightLabs/realopinsight-workstation#61]
Hi,

I have a map in RealOpInsight Ultimate, who have a IT probe in warning state because of a Disk Space Warning. This IT probe is decremented because it's a hardware and non critical service.

So my root business service, is in minor state. Here you can see the last QOS data inserted:

Timestamp,View,Status, Normal (%),Minor (%),Major (%),Critical (%),Unknown (%)
1420555275	view_name	1	98	0	2	0	0
1420555587	view_name	1	98	0	2	0	0
1420555900	view_name	1	98	0	2	0	0
1420556213	view_name	1	98	0	2	0	0
1420556525	view_name	1	98	0	2	0	0
1420556837	view_name	1	98	0	2	0	0
1420557101	view_name	1	98	0	2	0	0
1420557417	view_name	1	98	0	2	0	0

So I know my root business service is available, but SLA doesn't say that:

![rois_error_1](https://cloud.githubusercontent.com/assets/8058013/5701759/53cfbb50-9a50-11e4-92af-992096c9e587.png)

I don't understand why my SLA is about 0%.

Is it normal ?

Thank.

**Comment by jameseriot** [comment]
Hi @bzhpwr,
This is normal, because normal SLA is only enforced when the overall status of the top business service is Normal. In your case, regarding the timeline, there is not a period that your service was in normal state, meaning that your SLA is 0.

To do what you expect, you can set a aggregation rule on your top level service (or any other subservice) that makes you have a normal state status when there are subservices in minor state (e.g. with the default average aggregation rule, 2 normal states + 1 minor state should be converted to Normal.)

**Comment by jameseriot** [comment]
Alternatively, if the service does not have any importance for your business service, you could also set its weight to 0 (neutral). Then its status will be ignored when computing the status of its parent service.

**Comment by bzhpwr** [comment]
Hi @jameseriot

Really, Thank you for your second answer, it's what I'm looking for.

Every day your apps still surprise me.

Thank again, have a nice day.
