### ISSUE TITLE
data point names might not be unique and choosen at random

### ISSUE THREAD

**Issue by thermic** [RealOpInsightLabs/realopinsight-workstation#67]
Somethimes data point names pulled out of Zabbix are not unique, due to their nature. Consider the screen shot attached where trigger _name_ is not unique (It's a macro, a variable dynamically filled in). In the example screen shot, there are two triggers having a name such as "{ITEM.LASTVALUE2}".

In the realopinsight workstation applications, triggers show up as SourceX:Host/Trigger_Name, thus they're not uniquely identifiable, and I assume that realopinsight-ultimate would choose a trigger at random, since - from what I can see in the XML - there is no other identifier provided.

The only available work-around whould be to rework Zabbix triggers, but it might also be feasible to change the way realopinsight refers to Zabbix triggers, i.e. through their ID (triggerid). Nevertheless, that might impose new trouble for dynamically created items and triggers, so there's no best solution on how to deal with it.

Probably some notes in the manual would provide some insight on how exactly Zabbix items are referred to/looked up in realopinsight and what the limitations are.

![zabbix triggers](https://cloud.githubusercontent.com/assets/11552354/6729154/e5f46bc6-ce2f-11e4-8c20-5b6248c1daa2.png)

**Comment by jameseriot** [comment]
Hi,
First of all, it's OK to adding comments into RealOpInsight docs to warn about this situation.

Considering the situation, it's a matter of comprehension but  I think that rework Zabbix triggers would be better semantically speaking. Because, IMHO, having two or more than triggers assigned to the same host doing different things could be very confusing. 
I understand that this come from different templates, but to ease maintenability it may be also helpful to factorize templates to avoid having to triggers from two or more templates that do the same thing. 

But again, this requires to make a tradeoff. And we will consider a better work-around about this kind of issues.

**Comment by thermic** [comment]
> Because, IMHO, having two or more than triggers assigned to the same host doing different things could be very confusing.

In my case, a third-party system is delivering its alerts to Zabbix, consisting of classification and message. Depending on this external classification ("childstatus") we create a Zabbix event of certain severity (i.e. Information or Average), with the given message ("statusdescription"). But let us not get off-topic here, it's not the right place discussing Zabbix administration. -- It is an issue, and it hinders me from making full use of realopinsight.

**Comment by jameseriot** [comment]
Conceptual problem
